### ISSUE TITLE
Items not despawning

### ISSUE THREAD

**Issue by AnonymousPuppy** [ganymedes01/Gany-s-Surface#25]
I'm using a custom modpack, forge .1240, and Ganys Surface-1.9.4.jar. Items do not seem to despawn after 5 minutes. I pinpointed it down to this mod, and after removing it, they despawn like normal. I also made sure to disable the items not despawning when near the player feature, but it didn't seem to make a difference:

    # If there are any players within this radius of an item thrown on the ground that item will not despawn.
    # -Set it to 0 to disable this feature.
    # -Set it to LESS THAN 0 and items will never despawn regardless of players being nearby.
    I:noDespawnRadius=0

Please fix this as soon as possible, thank you :)

**Comment by ganymedes01** [comment]
Can't reproduce =/ Items are despawning fine for me

**Comment by ganymedes01** [comment]
Have you got any more information on this? I simply cannot reproduce it...
