### ISSUE TITLE
Doors and Chests has the wrong Thaumcraft aspects.

### ISSUE THREAD

**Issue by wmrojer** [ganymedes01/Gany-s-Surface#28]
The doors and chests that Gany's Surface adds only gets the default aspects from there recipes making them have less aspects then original doors and chests. They only have "Tree" on them since they are crafted from wood, but no aspects for the function.
Doors should have 1 Tree, 1 Motion and 1 Mechanism.
Chests should have 6 Tree and 4 Void.

Also all the new 1.8 stones have no aspects at all on them.

**Comment by ganymedes01** [comment]
Will fix.
To save me time form having to install Thaumcraft just to check this, the vanilla smooth stone has which aspects? Just 1 saxon?

**Comment by wmrojer** [comment]
I'll make a pull request for you. I'm working on it. It's just going to be the ThaumcraftManager.java

**Comment by ganymedes01** [comment]
Even better :)

**Comment by wmrojer** [comment]
You have given Tea Leaves the aspect PLANT, but since it is harvested from a plant it should probably be CROP to be consistent with the rest of the crops.
And Cooked egg is a PLANT?? Should probably be HUNGER. Want me to change those?

**Comment by ganymedes01** [comment]
Go for it :3

**Comment by wmrojer** [comment]
I'm done with the changes. Made a pull request. I haven't played around with Gany-s-Nether and Gany-s-End that much yet. I'll look into doing the same to those when I have gotten to know them better if that is ok with you.
