### ISSUE TITLE
Flint Block

### ISSUE THREAD

**Issue by Neodark7** [ganymedes01/Gany-s-Surface#30]
Even with 225+ mods, nobody add a flint block...
Can you add that ? :D

**Comment by ganymedes01** [comment]
Sure:3
Hardest part will be to make a texture for it XD

**Comment by Neodark7** [comment]
Here for you :)
![flint_block](https://cloud.githubusercontent.com/assets/7981869/6996077/8a64d388-db70-11e4-8cc0-ac8781fd0e70.png)

i've also made one for the charcoal block to be more like the coal block

![charcoal_block](https://cloud.githubusercontent.com/assets/7981869/6996080/9a3a4ca2-db70-11e4-8d9c-9cf7783b5cc2.png)

i can re-do them if you don't like it :)

**Comment by Neodark7** [comment]
here some "fullscreen" preview

Charcoal http://i.imgur.com/JBjvzyr.png
Flint http://i.imgur.com/wA7Tqx2.png

**Comment by ganymedes01** [comment]
Done:3
I wanted to make the block more "shiny", since the flint in game looks like a well polished rock (at least that's what I think lol), so I ended up just using the emerald block and tainting it black :D

Thanks for the textures though:3 Sorry I ended up not using them XD

**Comment by ganymedes01** [comment]
On that note, any more items that should be craftable into blocks? gunpowder would be nice, any other ideas?

**Comment by Neodark7** [comment]
Huu ok :( hmm ideas ? gunpowder block, potato block, carrot block, nether wart block, Bones block, blaze rods block, sugar block, ink sac block, dyes blocks, apple blocks, saplings blocks ? :D good luck with that

**Comment by Neodark7** [comment]
And leather block :p

**Comment by ganymedes01** [comment]
That's a lot of blocks XD I don't know if I like sapling or netherwart blocks, but the other ones seem reasonable.

[ ] Potato block
[ ] Carrot block
[ ] Bones block
[ ] Blaze rods block
[ ] Sugar block
[ ] Dyes block
[ ] Apple block
[ ] Leather block
