### ISSUE TITLE
Malisis' Doors compatibility

### ISSUE THREAD

**Issue by Adaptivity** [ganymedes01/Gany-s-Surface#32]
Malisis' Doors changes animations for doors, trap doors and fence gates. What about changing animation for Gany's Surface stuff? It would be veeeery cool :smile:
Mod page: http://minecraft.curseforge.com/mc-mods/223891-malisis-doors
Source: https://github.com/Ordinastie/MalisisDoors

**Comment by ganymedes01** [comment]
I'll see how hard it would be to do this. It does look very fancy :3

**Comment by Adaptivity** [comment]
@Ordinastie might want help you since he coded compatibility for Secret Rooms mod :smile:

**Comment by ganymedes01** [comment]
Closing this since I doubt I'll be adding this any time soon. It seems far too complicated and if I was to ever do it I'd do it in Et Futurum.
