### ISSUE TITLE
Plants not compatible with TE4's Phytogenic Isolator

### ISSUE THREAD

**Issue by medsal15** [ganymedes01/Gany-s-Surface#34]
The phytogenic isolator is a simple machine:
Inputs: Water (1000 mB), RF (depends on the goo), phyto-goo/rich phyto-goo and seed/plant
Output: Seed/plant and fruit/plant

**Comment by ganymedes01** [comment]
I'll look into adding support for it :)

**Comment by ganymedes01** [comment]
What version of TE4 has that block?
