### ISSUE TITLE
Dying armor removes enchantment

### ISSUE THREAD

**Issue by copygirl** [ganymedes01/Gany-s-Surface#39]
When dying enchanted, named or otherwise modified armor, all of the NBT data on the original item is lost in the crafting process.

**Comment by ganymedes01** [comment]
Easy fix. Thanks for letting me know:3

**Comment by ganymedes01** [comment]
Btw, just realised I don't have you on Headcurmbs!
Is your mc username "copygirl"?

**Comment by copygirl** [comment]
I technically have multiple MC accounts but the most used one is "copygirl", yes. Thanks <3

**Comment by ganymedes01** [comment]
Done:3
