### ISSUE TITLE
Recipe for sticks is missing with alternate wooden blocks recipes disabled

### ISSUE THREAD

**Issue by copygirl** [ganymedes01/Gany-s-Surface#43]

**Comment by ganymedes01** [comment]
The sticks are only used with the ladders, so if you disable them they also get disabled.

**Comment by copygirl** [comment]
The problem is that the recipe for regular sticks is missing.

**Comment by ganymedes01** [comment]
Right, yeah, I noticed it this morning. Fixed it earlier:3

**Comment by ganymedes01** [comment]
I've replied to your message on MCF btw :3

**Comment by copygirl** [comment]
Since you added the red sand option (you machine <3) I just used the whole mod (hence the bug reports). I don't suppose you've thought about automatically adding / enabling items for all wood types in the ore dictionary?

**Comment by ganymedes01** [comment]
I register the ones that have default names (like the sticks) and the ones that I use in my recipes (like the trapdoors), I guess registering all of them wouldn't hurt, I just don't know if there's a standard name for all of them (e.g. I wouldn't know what to register bookshelves as...) so that's why I didn't do it.

**Comment by copygirl** [comment]
Oh, sorry. I meant automatically creating, for example, stick and ladder items / blocks for any wood type that's in the ore dictionary, instead of hardcoding them.

**Comment by ganymedes01** [comment]
Oh right!
Well that would require dynamic texture generation, which is easy for some blocks (like the bookshelves) but impossible for stuff like the trapdoors (assuming you'd want a different design for each type of wood)

**Comment by copygirl** [comment]
My idea was to have a default template which can be overridden by supplying a custom texture (either by the mod itself, another mod, or a texture pack). This isn't a request by the way, just throwing some ideas out there.
