### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by cbcercas** [ganymedes01/Gany-s-Surface#46]
When I add Gany's Surface 1.11.0 on my server I get this crash http://paste.fedoraproject.org/215574/51055143/

Version 1.10.0 work

**Comment by ganymedes01** [comment]
"The paste you are looking for does not exist" )=

**Comment by cbcercas** [comment]
Sorry, here the crash report http://pastebin.com/17Gp6g0H

**Comment by ganymedes01** [comment]
Weird... Thaumcraft is the one crashing here.
Try disabling the Thaumcraft integration inside Gany's Surface and see if that fixes it.

**Comment by ganymedes01** [comment]
Also recommend reporting this to @Azanor

**Comment by ganymedes01** [comment]
Fixed on TC's side.
