### ISSUE TITLE
Polished Andesite recipe overwrites Botania's Andesite Brick recipe - Mod Compatibility

### ISSUE THREAD

**Issue by kurosnow** [ganymedes01/Gany-s-Surface#49]
As the title says. Botania also adds andesite, and has a recipe to turn it into bricks, and to turn it into polished. Botania's brick recipe is the same as your polished recipe, four andesite in a cube, but also has a recipe for polished being eight andesite in a circle.

Think you and Vazkii can figure something out? Gonna open the issue with Botania as well.

Thanks for your hard work Gany!

**Comment by kurosnow** [comment]
Update: This issue also affects Basalt and Granite. Basically all the 1.8 stones.

**Comment by ganymedes01** [comment]
Well the recipes I use are copied from 1.8, so I didn't really want to change them.

What do you think of this @Vazkii?

**Comment by Adaptivity** [comment]
@kurosnow as a temporary fix you can use [Gotolink's NoMoreRecipeConflict](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287599-gotolink-updates-formivores-fixes-2015-06-13-and#RecipeHandler). You can choose what do you want to craft in crafting table.

**Comment by ganymedes01** [comment]
Gany's Surface now has its own version of No Recipe Conflict type functionality. So this should no longer be a problem!
