### ISSUE TITLE
Missing textures in temple

### ISSUE THREAD

**Issue by Adaptivity** [ganymedes01/Gany-s-Surface#52]
My friend found this in temple: http://i.imgur.com/4HEPxpP.png
Forge: 1481
Ganys Surface: 1.11.1

**Comment by ganymedes01** [comment]
Thanks for your report!
I've fixed that issue, it was simply the wet sponge texture that I somehow forgot to paste into the resorces folder ಠ_ಠ
I'll see if I can release somethkng today. Thanks again!

**Comment by Adaptivity** [comment]
Lol, I knew you fixed it but was too lazy to check commits history :smile:
