### ISSUE TITLE
Chests can't be used in vanilla recipes

### ISSUE THREAD

**Issue by Adaptivity** [ganymedes01/Gany-s-Surface#54]
Tried to use new chests in hopper, minecart with chest, trapped chest recipes. Tested only with Gany's Surface.

**Comment by ganymedes01** [comment]
Right...
Forgot that Forge only merged the "chestWood" addition on 1.8.
I'll fixy it :3

**Comment by ganymedes01** [comment]
Minecart with Chest will remain using only the vanilla chest though
