### ISSUE TITLE
Crash Report - Maximum ID Range Exceeded

### ISSUE THREAD

**Issue by chloeprince** [ganymedes01/Gany-s-Surface#58]
I'm having the following error with Maximum ID Range being Exceeded.
This crash only happens when I add in Gany's Surface. Looks like its messing with AOBD Ore ID's.

Any help would be appreciated.

https://gist.github.com/chloeprince/dc91d255421fde07a33e

**Comment by ganymedes01** [comment]
Means you have too many mods that use too many IDs.
As far as I know, the only solution is to remove mods. Don't think there's a way around it unfortunately

**Comment by chloeprince** [comment]
I really just want the crafting table that this mod has. I have a lot of mods that have multiple recipes and I don't want to have to use mine tweaker to change them.

Could you make the Crafting Table a separate mod?

**Comment by Adaptivity** [comment]
Or you can use this: https://github.com/fewizz/NotEnoughIDs/releases However, this isn't compatible with already generated worlds.

**Comment by chloeprince** [comment]
The more I try this, and work with the configs, I ma still not convinced. I have a lot of ID's available. This mod, along with Gany's End and Nether are using excessive amounts of ID's for some odd reason.

I can add a bunch of other mods in addition to this pack, and I have no issues.
I've even removed a bunch of mods, including AOBD and still I am having the same error with this Surface, End and Nether Mods.

If you want to test my pack, you can do so here and add in these mods and try for yourself.
https://docs.google.com/spreadsheets/d/131cjBJKhUsLLiRZzW0x_VqdJS-RX6bHMWf68NUYCO3Q/edit#gid=776043935

I really hope you can relook at this. Possibly in how items are assigned ID"s.

**Comment by ganymedes01** [comment]
If you disable everything else it won't take up the IDs.
Also, there is already a mod that does just that, it's called "The No More Recipe Conflict Mod" I think. Not sure if it works exactly the same, but it should :3

**Comment by ganymedes01** [comment]
But it's strange that you're having this error with my mods only... I'll look into it. Thanks for letting me know :3

**Comment by Adaptivity** [comment]
@chloeprince can you make a dump of free block ids without Gany's mods and upload .csv file somewhere? It can be done in NEI.

**Comment by ganymedes01** [comment]
It would be very nice if you could do that Chloe. We would be able to tell if you are actually running out of IDs or if my mods somehow broke forge's registry system

**Comment by ganymedes01** [comment]
Closed because it's not my fault (as far as I know) and author didn't return with requested information.
