### ISSUE TITLE
Update Thaumcraft support

### ISSUE THREAD

**Issue by Adaptivity** [ganymedes01/Gany-s-Surface#64]
Chocolate cake should have 4 Aqua, 4 Fames, 4 Victus and 2 Sensus
All leaves walls should have 2 Herba
Sugar block should have 6 Fames.
Work table should have 4 Fabrico and 3 Vacuos
Dual work table should have 7 Fabrico and 5 Vacuos (Portable version should have same aspects)
Skeleton Horse, Max Stats Horse, Donkey, Mule eggs should have 1 Spiritus and 1 Vinculum
Also, @ganymedes01 can you change Quiver tooltip to support %s tag? I want to change it to Arrows: x(arrows count) (in ru_RU.lang)

**Comment by ganymedes01** [comment]
done and done!

**Comment by Adaptivity** [comment]
Hmm, [if (GanysSurface.enableChocolate)](https://github.com/ganymedes01/Gany-s-Surface/blob/master/src/main/java/ganymedes01/ganyssurface/integration/ThaumcraftManager.java#L46) and [if (GanysSurface.enableSpawnEggs)](https://github.com/ganymedes01/Gany-s-Surface/blob/master/src/main/java/ganymedes01/ganyssurface/integration/ThaumcraftManager.java#L56) already were there. Maybe it's better to add new stuff to them instead of adding new ones?
