### ISSUE TITLE
Button to remove items from crafting grid

### ISSUE THREAD

**Issue by Adaptivity** [ganymedes01/Gany-s-Surface#70]
Please, add "x" button to remove items from work tables. Similar to buttons in Forestry's Worktable. So, when you press "x" items from crafting grid should be moved back to player's inventory.

**Comment by ganymedes01** [comment]
I think this mod has got you covered: http://minecraft.curseforge.com/projects/crafting-tweaks

**Comment by Adaptivity** [comment]
This mod seems to add hotkeys but I would prefer buttons (small "x" button near crafting grid) instead since tons of mods adds keybinds to the game and there are hundred of conflicts. Is this hard to add?

**Comment by ganymedes01** [comment]
I'm not sure if you can disable the hotkeys, but I know it has buttons too.
Maybe @blay09 could let us know?

**Comment by blay09** [comment]
You can disable the hotkeys in the config file indeed. They'll still appear in the Controls menu, but won't interfere with other keys if there's conflicts. And yes, it adds buttons too.

**Comment by Adaptivity** [comment]
Ok, thanks for the info :+1:
