### ISSUE TITLE
Not an issue - German Translation

### ISSUE THREAD

**Issue by QuImUfu** [ganymedes01/Gany-s-Surface#74]
I wrote a complete German translation:
https://dl.dropboxusercontent.com/s/sik17c8z13bc390/de_DE.lang?dl=0

(i do not understand the Pull request system)

**Comment by ganymedes01** [comment]
No problem. I'll merge your changes myself.

I recommend you try learning about PRs though, it's really easy to use and it will make it a lot easier to merge your translations in the future :)
